# Generated by Django 4.2 on 2023-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base51", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesender",
            name="sms_response",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
