# Generated by Django 4.2 on 2023-05-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base51", "0002_messagesender_sms_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagesender",
            name="sms_response",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base51.smsresponse",
            ),
        ),
    ]
